package view;

import controller.Controller;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifhnomura
 */
public class JanelaProcuraUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JanelaProcuraUsuario
     */
    public JanelaProcuraUsuario() {
        initComponents();
        Controller control = control;
    }

    public JButton getBtUserSearch() {
        return btUserSearch;
    }

    public void setBtUserSearch(JButton btUserSearch) {
        this.btUserSearch = btUserSearch;
    }

    public JLabel getLbUserSearch() {
        return lbUserSearch;
    }

    public void setLbUserSearch(JLabel lbUserSearch) {
        this.lbUserSearch = lbUserSearch;
    }

    public JTextField getTxtExibirPesquisa() {
        return txtExibirPesquisa;
    }

    public void setTxtExibirPesquisa(JTextField txtExibirPesquisa) {
        this.txtExibirPesquisa = txtExibirPesquisa;
    }

    public JTextField getTxtUserSearch() {
        return txtUserSearch;
    }

    public void setTxtUserSearch(JTextField txtUserSearch) {
        this.txtUserSearch = txtUserSearch;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUserSearch = new javax.swing.JLabel();
        txtUserSearch = new javax.swing.JTextField();
        btUserSearch = new javax.swing.JButton();
        txtExibirPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Procura Usuário");

        lbUserSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbUserSearch.setText("Procurar usuário por CPF");

        btUserSearch.setText("Exibir");
        btUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btUserSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtExibirPesquisa)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUserSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btUserSearch)
                .addGap(18, 18, 18)
                .addComponent(txtExibirPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserSearchActionPerformed
        control.teste();
        String usuario = control.controlProcuraUsuario();
        if(usuario.equals("0")){
        System.out.println("nao tem nada");
        } else{
            System.out.println(usuario);
        }      
    }//GEN-LAST:event_btUserSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaProcuraUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaProcuraUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaProcuraUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaProcuraUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaProcuraUsuario().setVisible(true);
            }
        });
    }
    private Controller control;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btUserSearch;
    private javax.swing.JLabel lbUserSearch;
    private javax.swing.JTextField txtExibirPesquisa;
    private javax.swing.JTextField txtUserSearch;
    // End of variables declaration//GEN-END:variables
}
